# Generated by Django 5.1.2 on 2025-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
