# Generated by Django 5.1.2 on 2025-01-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan', '0002_course_video_alter_learner_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='megan.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_question', models.TextField()),
                ('choix_1', models.CharField(max_length=255)),
                ('choix_2', models.CharField(max_length=255)),
                ('choix_3', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='megan.quiz')),
            ],
        ),
    ]
