# Generated by Django 5.1.2 on 2025-01-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan', '0003_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=255)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='megan.learner')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='megan.question')),
            ],
        ),
    ]
