# Generated by Django 5.1.2 on 2025-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megan', '0004_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
